import { ACADEMY_SCHOOLS, IRRIGATION_LEVEL_FRAMEWORK } from './academyCatalog.js';

const REVISION_DATE = '2026-08-05';

const lesson = (schoolSlug, number, title, objectiveIds, content) => ({
  id: `academy-lesson-${schoolSlug}-${number}`,
  schoolId: `academy-school-${schoolSlug}`,
  courseId: `academy-course-${schoolSlug}-foundations`,
  levelId: `academy-level-${schoolSlug}-1`,
  moduleId: `academy-module-${schoolSlug}-${number}`,
  title,
  learningObjectives: objectiveIds,
  prerequisites: number === 1 ? [] : [`academy-lesson-${schoolSlug}-${number - 1}`],
  estimatedMinutes: 24,
  origin: 'built-in',
  status: 'published',
  revisionDate: REVISION_DATE,
  ...content,
});

const question = (schoolSlug, number, objectiveId, type, prompt, options, correctAnswer, explanation, extras = {}) => ({
  id: `academy-question-${schoolSlug}-${number}`,
  objectiveId,
  topic: schoolSlug,
  difficulty: extras.difficulty || (number % 6 === 0 ? 3 : number % 3 === 0 ? 2 : 1),
  type,
  prompt,
  promptVariants: extras.promptVariants || [],
  scenarioVariables: extras.scenarioVariables || {},
  options: options || [],
  correctAnswer,
  correctAnswerCriteria: extras.correctAnswerCriteria || [],
  explanation,
  misconceptionTags: extras.misconceptionTags || [],
});

function buildCourse(config) {
  const school = ACADEMY_SCHOOLS.find(item => item.slug === config.slug);
  const levelId = `academy-level-${config.slug}-1`;
  return {
    school,
    course: {
      id: `academy-course-${config.slug}-foundations`,
      schoolId: school.id,
      title: config.courseTitle,
      summary: config.courseSummary,
      origin: 'built-in',
      levelIds: [levelId],
    },
    levels: [{
      id: levelId,
      schoolId: school.id,
      courseId: `academy-course-${config.slug}-foundations`,
      number: 1,
      title: config.levelTitle,
      summary: config.levelSummary,
      moduleIds: config.lessons.map((_, index) => `academy-module-${config.slug}-${index + 1}`),
      lessonIds: config.lessons.map((_, index) => `academy-lesson-${config.slug}-${index + 1}`),
      objectiveIds: config.objectives.map(item => item.id),
      vocabularyActivityId: `academy-vocabulary-${config.slug}-1`,
      practiceActivityId: `academy-practice-${config.slug}-1`,
      scenarioAssessmentId: `academy-scenario-${config.slug}-1`,
      fieldLabId: `academy-field-lab-${config.slug}-1`,
      designChallengeId: config.designChallenge ? `academy-design-challenge-${config.slug}-1` : '',
      finalAssessmentId: `academy-final-${config.slug}-1`,
      masteryThreshold: 85,
      status: 'complete',
    }],
    modules: config.lessons.map((item, index) => ({
      id: `academy-module-${config.slug}-${index + 1}`,
      levelId,
      title: item.moduleTitle,
      summary: item.moduleSummary,
      lessonIds: [`academy-lesson-${config.slug}-${index + 1}`],
    })),
    lessons: config.lessons.map((item, index) => lesson(config.slug, index + 1, item.title, item.objectiveIds, item)),
    objectives: config.objectives.map(item => ({ ...item, schoolId: school.id, levelId })),
    vocabulary: {
      id: `academy-vocabulary-${config.slug}-1`,
      levelId,
      title: `${config.levelTitle} vocabulary`,
      objectiveIds: config.objectives.map(item => item.id),
      terms: config.vocabulary,
    },
    practice: {
      id: `academy-practice-${config.slug}-1`,
      levelId,
      objectiveIds: config.objectives.map(item => item.id),
      ...config.practice,
    },
    scenarioAssessment: {
      id: `academy-scenario-${config.slug}-1`,
      levelId,
      title: `${config.levelTitle} scenario assessment`,
      type: 'scenario',
      questionCount: 3,
      objectiveIds: config.objectives.map(item => item.id),
    },
    fieldLab: {
      id: `academy-field-lab-${config.slug}-1`,
      levelId,
      objectiveIds: config.objectives.map(item => item.id),
      ...config.fieldLab,
    },
    designChallenge: config.designChallenge ? {
      id: `academy-design-challenge-${config.slug}-1`,
      levelId,
      objectiveIds: config.objectives.map(item => item.id),
      ...config.designChallenge,
    } : null,
    finalAssessment: {
      id: `academy-final-${config.slug}-1`,
      levelId,
      title: `${config.levelTitle} final assessment`,
      type: 'final',
      questionCount: 5,
      objectiveIds: config.objectives.map(item => item.id),
    },
    questions: config.questions,
  };
}

const configs = [
  {
    slug: 'horticulture-foundations',
    courseTitle: 'Practical Horticulture Foundations',
    courseSummary: 'Read a landscape as a living system and make careful, site-based plant decisions.',
    levelTitle: 'Level 1 · Plants, Sites, and Care',
    levelSummary: 'Plant needs, site observations, and an evidence-based maintenance loop.',
    objectives: [
      { id: 'obj-hort-site-fit', title: 'Match plant needs to site conditions', reviewLessonId: 'academy-lesson-horticulture-foundations-1', reviewSection: 'Plant–site fit', remediation: 'Compare two possible planting locations using light, moisture, and mature size.' },
      { id: 'obj-hort-growth', title: 'Explain how growth changes through a season', reviewLessonId: 'academy-lesson-horticulture-foundations-2', reviewSection: 'Growth and season', remediation: 'Build a four-season observation timeline for one plant.' },
      { id: 'obj-hort-care', title: 'Use observation before intervention', reviewLessonId: 'academy-lesson-horticulture-foundations-3', reviewSection: 'Observe–interpret–act', remediation: 'Write three observations before naming a treatment.' },
    ],
    lessons: [
      { moduleTitle: 'Plant–site fit', moduleSummary: 'Start with conditions, not a shopping list.', title: 'Read the site before choosing the plant', objectiveIds: ['obj-hort-site-fit'], introduction: 'Successful horticulture begins by comparing what a plant needs with what a place can reliably provide.', body: ['Record hours and timing of direct sun instead of relying only on “sun” or “shade.” Buildings and trees can change that pattern across the year.', 'Observe drainage, exposure, reflected heat, wind, salt, foot traffic, root competition, and the space available at mature size. A healthy nursery plant can still be a poor site match.', 'Treat hardiness-zone information as one screen, not a guarantee. Soil moisture, heat, wind, siting, and unusual weather also affect survival.'], keyConcepts: ['Plant requirements must be compared with measured site conditions.', 'Mature size is a design and maintenance constraint.', 'Zone ratings do not replace local observation.'], vocabulary: ['microclimate', 'exposure', 'hardiness'], workedExamples: ['A west-facing brick wall can create hotter, drier conditions than another bed in the same yard.'], practicalApplication: 'Make a site card before proposing a plant.', clientRelevance: 'Explain that site fit protects the client’s investment and reduces replacement risk.', commonMistakes: ['Choosing by flower color before checking conditions', 'Using current plant size as the spacing guide'], safetyNotes: ['Do not dig until utilities and site hazards are considered.'], businessRelevance: 'Documented conditions make substitutions and warranty conversations clearer.', quickChecks: ['Name three conditions beyond sunlight.', 'Why is mature width a current design concern?'], summary: 'Choose from the site outward.', sourceNotes: 'Original Tierra Fleur instructional summary informed by standard horticultural site-assessment practice.' },
      { moduleTitle: 'Growth through time', moduleSummary: 'Understand the seasonal rhythm behind visible change.', title: 'Think in life cycles and seasonal growth', objectiveIds: ['obj-hort-growth'], introduction: 'Plants allocate energy differently during establishment, active growth, flowering, fruiting, dormancy, and stress.', body: ['New growth depends on stored resources, current photosynthesis, water, temperature, and the condition of roots and shoots. Fast visible growth is not the only sign of progress.', 'Annuals, biennials, herbaceous perennials, woody plants, and evergreens organize their life cycles differently. Care timing should match the plant and the goal.', 'Avoid forcing growth at the wrong time. Heavy fertilization, pruning, or repeated watering can create weak growth or interfere with dormancy and root function.'], keyConcepts: ['Life cycle affects maintenance timing.', 'Roots and shoots share limited resources.', 'Dormancy is a normal strategy, not automatically a failure.'], vocabulary: ['annual', 'perennial', 'dormancy'], workedExamples: ['A newly planted shrub may show modest shoot growth while roots establish.'], practicalApplication: 'Create a seasonal care timeline for one installed plant.', clientRelevance: 'Set realistic expectations for first-year growth and appearance.', commonMistakes: ['Assuming dormant means dead', 'Fertilizing to solve every slow-growth problem'], safetyNotes: ['Use pruning tools and products according to their labels and safe operating instructions.'], businessRelevance: 'Seasonal expectations reduce avoidable callbacks.', quickChecks: ['How can establishment redirect plant resources?', 'Why can late soft growth be risky?'], summary: 'Time care to the plant’s actual growth stage.', sourceNotes: 'Original instructional synthesis; confirm species-specific timing with current extension guidance.' },
      { moduleTitle: 'Care decisions', moduleSummary: 'Build a repeatable observation loop.', title: 'Observe, interpret, act, and verify', objectiveIds: ['obj-hort-care'], introduction: 'A professional care decision separates what is visible from what is merely suspected.', body: ['Begin with observable facts: location, pattern, affected plant parts, timing, weather, soil moisture, and recent changes. Avoid jumping from one symptom to one cause.', 'Form a short list of plausible explanations and use safe checks to separate them. A wilted plant may be dry, waterlogged, root-damaged, heat-stressed, or affected by disease.', 'Choose the lowest-risk useful action, document it, and schedule a follow-up. If evidence is insufficient or the issue could be hazardous, seek qualified local help.'], keyConcepts: ['Symptoms can have multiple causes.', 'Patterns and timing narrow possibilities.', 'Follow-up is part of the intervention.'], vocabulary: ['symptom', 'sign', 'monitoring'], workedExamples: ['Before watering a wilted shrub, check moisture at root depth and inspect the pattern across the bed.'], practicalApplication: 'Write an observation note that contains no diagnosis, then add possible causes.', clientRelevance: 'Use careful language such as “consistent with” when the evidence is incomplete.', commonMistakes: ['Treating before checking soil moisture', 'Promising certainty from one photo'], safetyNotes: ['Do not taste plants or handle unknown irritants without appropriate precautions.'], businessRelevance: 'Records protect continuity when more than one person visits a site.', quickChecks: ['What is the difference between a symptom and a sign?', 'What closes the care loop?'], summary: 'Act from evidence and verify the result.', sourceNotes: 'Original instructional writing based on diagnostic process principles.' },
    ],
    vocabulary: [{ term: 'Microclimate', definition: 'Conditions in a small area that differ from the surrounding site.' }, { term: 'Hardiness', definition: 'A plant’s ability to tolerate specified cold conditions; not a complete site-fit measure.' }, { term: 'Dormancy', definition: 'A period of reduced visible growth and activity.' }, { term: 'Symptom', definition: 'A plant response such as yellowing or wilting.' }, { term: 'Sign', definition: 'Direct evidence of a causal organism or agent.' }, { term: 'Monitoring', definition: 'Scheduled observation used to detect change and evaluate action.' }],
    practice: { title: 'Three-location site comparison', instructions: 'Compare three planting locations. Record sun timing, moisture, exposure, available mature width, and one uncertainty for each.', checklist: ['Three locations recorded', 'Conditions separated from assumptions', 'Mature space considered', 'One follow-up observation scheduled'] },
    fieldLab: { title: 'Plant–site fit field observation', instructions: 'Choose one real plant and location. Photograph or describe the plant, record light and soil-moisture observations, measure available width, and write a fit recommendation.', safetyNotes: 'Observe from a safe location. Do not dig or handle an unknown plant for this lab.', requiredEvidence: ['date', 'locationCategory', 'measurements', 'notes'], photoOptional: true, checklist: ['Plant and place recorded', 'At least three site conditions observed', 'Available width measured', 'Recommendation includes uncertainty'] },
    questions: [
      question('horticulture-foundations', 1, 'obj-hort-site-fit', 'multiple-choice', 'Which action should come first when a client requests a flowering shrub?', ['Choose a favorite color', 'Measure and observe the planting site', 'Order the largest available container', 'Promise a bloom date'], 'Measure and observe the planting site', 'Site conditions define the responsible plant palette.', { promptVariants: ['Before recommending a shrub, what should the designer do first?', 'What is the best starting point for a plant recommendation?'] }),
      question('horticulture-foundations', 2, 'obj-hort-site-fit', 'multiple-select', 'Which observations help establish plant–site fit?', ['Sun timing', 'Drainage', 'Mature space', 'Pot color'], ['Sun timing', 'Drainage', 'Mature space'], 'Light, water movement, and mature space are relevant site conditions.'),
      question('horticulture-foundations', 3, 'obj-hort-growth', 'true-false', 'A dormant perennial should automatically be classified as dead.', ['True', 'False'], 'False', 'Dormancy is a normal life-cycle strategy.', { promptVariants: ['True or false: lack of winter top growth always proves plant failure.'] }),
      question('horticulture-foundations', 4, 'obj-hort-growth', 'multiple-choice', 'Why might a newly planted shrub show limited shoot growth?', ['Roots may be establishing', 'It must need fertilizer', 'Its mature size is fixed', 'All shrubs stop growing after planting'], 'Roots may be establishing', 'Establishment can redirect resources toward roots.'),
      question('horticulture-foundations', 5, 'obj-hort-care', 'multiple-choice', 'A shrub wilts after several rainy days. What is the safest first check?', ['Add more water', 'Check moisture and drainage at root depth', 'Apply insecticide', 'Prune every branch'], 'Check moisture and drainage at root depth', 'Wilting can occur in both dry and waterlogged conditions.', { promptVariants: ['After wet weather, a plant droops. Which observation is most useful before treatment?'] }),
      question('horticulture-foundations', 6, 'obj-hort-care', 'short-response', 'At a {site}, list two objective observations to record before diagnosing a declining plant.', [], [], 'Useful observations include pattern, timing, affected part, soil moisture, weather, and recent changes.', { correctAnswerCriteria: ['pattern', 'timing', 'soil', 'moisture', 'weather', 'location', 'affected', 'change'], scenarioVariables: { site: ['foundation planting', 'container grouping', 'mixed perennial bed'] } }),
    ],
  },
  {
    slug: 'soil-science',
    courseTitle: 'Soil and Nutrition Foundations',
    courseSummary: 'Use texture, structure, drainage, organic matter, pH, and evidence to plan soil care.',
    levelTitle: 'Level 1 · Soil as a Living Root Environment',
    levelSummary: 'Observe soil behavior and choose measured, defensible improvements.',
    objectives: [
      { id: 'obj-soil-texture', title: 'Distinguish texture from structure', reviewLessonId: 'academy-lesson-soil-science-1', reviewSection: 'Texture and structure', remediation: 'Compare how two soils form ribbons and aggregates without naming them from color alone.' },
      { id: 'obj-soil-water', title: 'Interpret infiltration and drainage observations', reviewLessonId: 'academy-lesson-soil-science-2', reviewSection: 'Water in soil', remediation: 'Repeat a drainage observation and record test dimensions, timing, and recent rainfall.' },
      { id: 'obj-soil-amend', title: 'Choose amendments from evidence and goals', reviewLessonId: 'academy-lesson-soil-science-3', reviewSection: 'Evidence before amendment', remediation: 'Rewrite an amendment recommendation to include a measured reason and verification plan.' },
    ],
    lessons: [
      { moduleTitle: 'Soil physical properties', moduleSummary: 'Separate particle size from aggregation.', title: 'Texture, structure, pores, and compaction', objectiveIds: ['obj-soil-texture'], introduction: 'Roots depend on a balance of mineral particles, organic matter, water, air, and living organisms.', body: ['Texture describes the relative proportions of sand, silt, and clay. It changes slowly and influences water retention, nutrient holding, and workability.', 'Structure describes how particles form aggregates and pore spaces. Management can improve or damage structure even when texture remains unchanged.', 'Compaction reduces large pores, limiting infiltration, drainage, gas exchange, and root growth. Avoid working or driving on wet soil when it deforms easily.'], keyConcepts: ['Texture and structure are different properties.', 'Pore sizes influence air and water movement.', 'Compaction is a physical constraint.'], vocabulary: ['texture', 'structure', 'aggregate', 'compaction'], workedExamples: ['A clay-textured soil can still have useful structure when stable aggregates create connected pores.'], practicalApplication: 'Describe a soil using texture clues and structural observations separately.', clientRelevance: 'Explain why adding a small amount of sand is not a universal repair for clay soil.', commonMistakes: ['Calling every dense soil clay', 'Judging texture by color'], safetyNotes: ['Wear gloves and avoid testing soil suspected of contamination.'], businessRelevance: 'Accurate soil language supports realistic scope and pricing.', quickChecks: ['Can management change texture quickly?', 'How does compaction affect roots?'], summary: 'Texture is the particle mix; structure is the arrangement.', sourceNotes: 'Original summary aligned with standard soil-science terminology.' },
      { moduleTitle: 'Water in soil', moduleSummary: 'Read infiltration, drainage, and storage.', title: 'Follow water through the root zone', objectiveIds: ['obj-soil-water'], introduction: 'Water must enter soil, move through it, remain available to roots, and leave enough pore space for oxygen.', body: ['Infiltration is entry at the surface; percolation is movement through soil. Drainage describes removal of excess water from the root zone and site.', 'Field capacity is the water remaining after free drainage; permanent wilting point is a lower threshold beyond which a plant cannot recover turgor without added water. The usable range varies by soil and plant.', 'A simple drainage observation is only a screening tool. Hole dimensions, pre-soaking, recent rainfall, fill depth, and elapsed time must be recorded to interpret it honestly.'], keyConcepts: ['Infiltration and drainage are not synonyms.', 'Not all retained water is plant-available.', 'A field test needs documented conditions.'], vocabulary: ['infiltration', 'percolation', 'field capacity', 'wilting point'], workedExamples: ['A crusted surface may shed water even when the subsoil could transmit it.'], practicalApplication: 'Map where water enters, collects, and exits on one property.', clientRelevance: 'Avoid promising a drainage solution from one shallow test.', commonMistakes: ['Testing immediately after extreme rain without noting it', 'Equating slow infiltration with one guaranteed cause'], safetyNotes: ['Do not create unattended holes or test near utilities.'], businessRelevance: 'Water observations inform planting, grading referrals, and irrigation scope.', quickChecks: ['What is the difference between infiltration and percolation?', 'Why record recent rainfall?'], summary: 'Measure water movement with context.', sourceNotes: 'Original educational summary; local codes and site professionals govern drainage work.' },
      { moduleTitle: 'Nutrition decisions', moduleSummary: 'Use tests and plant goals before adding products.', title: 'pH, nutrients, organic matter, and amendments', objectiveIds: ['obj-soil-amend'], introduction: 'Good soil care asks what limitation exists, what outcome is needed, and how the result will be checked.', body: ['Soil pH influences nutrient availability and biology, but a target depends on the crop and local soil. Change pH only from a reliable test and a calculated recommendation.', 'Plant nutrients are essential in different amounts. Deficiency-like symptoms can also result from root injury, pH, water stress, disease, or excessive nutrients.', 'Organic matter can support aggregation and water behavior, but more is not always better. Match amendment type, amount, placement, and timing to the site and plant.'], keyConcepts: ['Test before correcting pH or nutrients.', 'Symptoms alone do not prove deficiency.', 'Amendments have rates and tradeoffs.'], vocabulary: ['pH', 'macronutrient', 'micronutrient', 'organic matter'], workedExamples: ['Yellow leaves in waterlogged soil may reflect root dysfunction rather than a shortage corrected by fertilizer.'], practicalApplication: 'Turn a soil-test result into a cautious action and verification plan.', clientRelevance: 'Explain why a measured recommendation is more valuable than a generic product list.', commonMistakes: ['Fertilizing from leaf color alone', 'Amending only the planting hole with a radically different mix'], safetyNotes: ['Follow product labels and protect waterways from runoff.'], businessRelevance: 'Document products, rates, and reasons for material estimates and follow-up.', quickChecks: ['Why can a nutrient be present but unavailable?', 'What makes an amendment recommendation defensible?'], summary: 'Use evidence, appropriate rates, and follow-up.', sourceNotes: 'Original summary; use current laboratory and extension recommendations for site-specific rates.' },
    ],
    vocabulary: [{ term: 'Texture', definition: 'Relative proportion of sand, silt, and clay.' }, { term: 'Structure', definition: 'Arrangement of soil particles into aggregates and pores.' }, { term: 'Infiltration', definition: 'Entry of water through the soil surface.' }, { term: 'Percolation', definition: 'Movement of water through soil.' }, { term: 'Field capacity', definition: 'Water held after excess gravitational water has drained.' }, { term: 'pH', definition: 'A measure related to acidity or alkalinity that affects soil processes.' }],
    practice: { title: 'Soil evidence worksheet', instructions: 'Record texture clues, aggregation, surface condition, compaction clues, moisture, and one test you would request before recommending an amendment.', checklist: ['Texture and structure recorded separately', 'Water evidence included', 'Uncertainty named', 'Recommendation deferred until appropriate evidence'] },
    fieldLab: { title: 'Documented drainage observation', instructions: 'Perform a safe, simple drainage observation in an appropriate location. Record dimensions, initial conditions, fill depth, elapsed time, weather context, and what the result can and cannot establish.', safetyNotes: 'Check for utilities and property permission. Keep holes visible and supervised; backfill promptly. Do not treat this as an engineered percolation or permitting test.', requiredEvidence: ['date', 'locationCategory', 'measurements', 'notes'], photoOptional: true, checklist: ['Permission and safe location confirmed', 'Dimensions and timing recorded', 'Recent weather recorded', 'Limitations stated'] },
    questions: [
      question('soil-science', 1, 'obj-soil-texture', 'multiple-choice', 'Which property describes the proportion of sand, silt, and clay?', ['Structure', 'Texture', 'Fertility', 'Color'], 'Texture', 'Texture is the mineral particle-size distribution.', { promptVariants: ['Sand, silt, and clay proportions define which soil property?'] }),
      question('soil-science', 2, 'obj-soil-texture', 'true-false', 'Improving aggregation can change soil structure without changing its texture.', ['True', 'False'], 'True', 'Management can affect aggregation and pores while particle-size proportions remain stable.'),
      question('soil-science', 3, 'obj-soil-water', 'multiple-choice', 'Water entering through the soil surface is called:', ['Infiltration', 'Transpiration', 'Dormancy', 'Germination'], 'Infiltration', 'Infiltration describes entry at the surface.'),
      question('soil-science', 4, 'obj-soil-water', 'multiple-select', 'At a {site}, which details make a drainage observation interpretable?', ['Hole dimensions', 'Elapsed time', 'Recent rainfall', 'The tester’s favorite plant'], ['Hole dimensions', 'Elapsed time', 'Recent rainfall'], 'Test geometry, timing, and starting conditions provide context.', { scenarioVariables: { site: ['new foundation bed', 'sloped backyard bed', 'future berry planting'] } }),
      question('soil-science', 5, 'obj-soil-amend', 'multiple-choice', 'A plant has yellow leaves in saturated soil. What is the best next step?', ['Assume nitrogen deficiency', 'Investigate roots, moisture, and the pattern before fertilizing', 'Add lime immediately', 'Double every amendment'], 'Investigate roots, moisture, and the pattern before fertilizing', 'Water stress and root dysfunction can resemble nutrient problems.', { promptVariants: ['Yellow foliage appears where water collects. Which response is most defensible?'] }),
      question('soil-science', 6, 'obj-soil-amend', 'short-response', 'Name two pieces of evidence that can support a soil amendment decision.', [], [], 'A laboratory soil test, physical observations, plant needs, measured area, and product label or calculated rate can be relevant.', { correctAnswerCriteria: ['test', 'observation', 'plant', 'area', 'rate', 'label', 'pH'] }),
    ],
  },
  {
    slug: 'landscape-design',
    courseTitle: 'Landscape Design Foundations',
    courseSummary: 'Translate site and client evidence into a functional, coherent concept.',
    levelTitle: 'Level 1 · Site, Function, and Composition',
    levelSummary: 'A practical route from consultation and analysis to a requirement-based concept review.',
    objectives: [
      { id: 'obj-design-analysis', title: 'Build a site and client analysis', reviewLessonId: 'academy-lesson-landscape-design-1', reviewSection: 'Evidence before form', remediation: 'Separate one design brief into goals, constraints, preferences, and unknowns.' },
      { id: 'obj-design-principles', title: 'Use scale, balance, rhythm, and unity intentionally', reviewLessonId: 'academy-lesson-landscape-design-2', reviewSection: 'Composition', remediation: 'Annotate where repetition, contrast, and focal emphasis occur in a small bed.' },
      { id: 'obj-design-planting', title: 'Plan layers using mature size and seasonal function', reviewLessonId: 'academy-lesson-landscape-design-3', reviewSection: 'Planting over time', remediation: 'Redraw a plant group at mature width and check access and maintenance.' },
    ],
    lessons: [
      { moduleTitle: 'Brief and analysis', moduleSummary: 'Define the real design problem.', title: 'Turn client goals and site facts into a design brief', objectiveIds: ['obj-design-analysis'], introduction: 'A strong concept responds to a documented problem rather than decorating an incomplete idea.', body: ['Record how the space must function: users, circulation, access, views, privacy, maintenance, harvest, play, rest, storage, and seasonal use.', 'Map sun, water, slope, soil clues, utilities, doors, windows, downspouts, property boundaries, existing plants, and important sight lines. Mark what has been measured and what remains approximate.', 'Separate requirements from preferences. Budget, safe access, mature space, and drainage are constraints; a favorite color or garden style is usually a preference. Confirm the brief before developing detail.'], keyConcepts: ['Function precedes decoration.', 'Existing conditions shape the concept.', 'Unknowns should remain visible.'], vocabulary: ['program', 'constraint', 'circulation', 'site analysis'], workedExamples: ['“English garden” becomes loose seasonal color, fragrance near the entry, a clear path, and manageable upkeep.'], practicalApplication: 'Create a one-page design brief for a practice property.', clientRelevance: 'A written brief makes approvals and exclusions understandable.', commonMistakes: ['Drawing beds before confirming use', 'Hiding unmeasured assumptions'], safetyNotes: ['Site observation does not replace utility location, surveys, engineering, or permits.'], businessRelevance: 'A confirmed brief limits unpaid redesign caused by unclear scope.', quickChecks: ['What is the difference between a requirement and a preference?', 'Name two site unknowns that should be verified.'], summary: 'Define the problem before shaping the answer.', sourceNotes: 'Original landscape-design instruction; regulated site work requires appropriate local professionals.' },
      { moduleTitle: 'Composition', moduleSummary: 'Use design principles as decision tools.', title: 'Organize scale, balance, rhythm, unity, and contrast', objectiveIds: ['obj-design-principles'], introduction: 'Design principles describe relationships; they are not a formula that guarantees subjective quality.', body: ['Scale and proportion compare parts to people, buildings, spaces, and each other. Balance distributes visual weight and can be symmetrical or asymmetrical.', 'Rhythm comes from repetition and sequence. Unity makes a design read as related; contrast creates distinction and can support a focal point.', 'Color, texture, and form change with distance, light, growth, and season. Use a limited hierarchy: a clear dominant idea, supporting patterns, and controlled variation.'], keyConcepts: ['Principles describe relationships.', 'Repetition can create rhythm and unity.', 'Contrast needs a purpose.'], vocabulary: ['scale', 'proportion', 'rhythm', 'unity'], workedExamples: ['Repeating an ornamental grass at path turns creates rhythm while one small tree anchors the view.'], practicalApplication: 'Annotate a concept with one example of four design principles.', clientRelevance: 'Explain choices through function and relationships rather than taste alone.', commonMistakes: ['Using one of every favorite plant', 'Making every feature a focal point'], safetyNotes: ['Keep circulation widths, visibility, and trip risks in the design review.'], businessRelevance: 'A legible concept is easier to estimate and revise.', quickChecks: ['How can repetition differ from monotony?', 'What creates visual weight?'], summary: 'Build a hierarchy of related forms and useful contrast.', sourceNotes: 'Original instructional synthesis of established landscape-design principles.' },
      { moduleTitle: 'Planting plan', moduleSummary: 'Design in mature dimensions and seasons.', title: 'Layer plants for mature size, access, and change', objectiveIds: ['obj-design-planting'], introduction: 'A planting plan must work after nursery-sized plants grow and after peak bloom passes.', body: ['Place structural plants first, then seasonal and ground layers. Check mature height and width against windows, paths, foundations, utilities, views, and one another.', 'Spacing is not a single universal number. Plant habit, desired time to coverage, air movement, maintenance access, budget, and client expectations all matter.', 'Plan bloom, foliage, fruit, bark, texture, and dormancy across seasons. Include access for pruning, harvest, inspection, replacement, and irrigation maintenance.'], keyConcepts: ['Draw and estimate with mature dimensions.', 'Layering combines vertical and seasonal roles.', 'Maintenance access is part of composition.'], vocabulary: ['layering', 'mature spread', 'seasonal interest', 'hydro-zone'], workedExamples: ['A foundation bed keeps shrubs below windows at maturity and places harvestable herbs near the path edge.'], practicalApplication: 'Build a small plant schedule with role, mature size, spacing rationale, and season.', clientRelevance: 'Explain the intended establishment period and what may look open in year one.', commonMistakes: ['Overplanting for instant fullness', 'Ignoring dormant appearance'], safetyNotes: ['Verify toxicity, thorns, visibility, and access where users or pets may contact plants.'], businessRelevance: 'Mature-size planning reduces preventable removals and warranty conflict.', quickChecks: ['Why can spacing vary for the same species?', 'What should a four-season review include?'], summary: 'Design the future garden, not the nursery cart.', sourceNotes: 'Original instruction; verify plant traits in existing Plant Intelligence records and reliable current sources.' },
    ],
    vocabulary: [{ term: 'Program', definition: 'The uses and requirements a design must support.' }, { term: 'Scale', definition: 'Size in relation to people, buildings, spaces, or other elements.' }, { term: 'Rhythm', definition: 'A sense of movement created by repetition and sequence.' }, { term: 'Unity', definition: 'The perception that design parts belong together.' }, { term: 'Focal point', definition: 'An intentionally emphasized feature or view.' }, { term: 'Mature spread', definition: 'Expected plant width at maturity under stated conditions.' }],
    practice: { title: 'Requirement-based concept review', instructions: 'Review a small concept against its brief. Mark circulation, one focal point, mature widths, seasonal structure, maintenance access, and budget-sensitive choices.', checklist: ['Brief requirements traced to design elements', 'Mature widths checked', 'Circulation and access checked', 'One revision priority recorded'] },
    fieldLab: { title: 'Measure and analyze a small bed', instructions: 'Measure an existing bed and key nearby features. Record sun, access, current plants, drainage clues, views, and at least one uncertainty. Create a simple dimensioned field sketch or photo annotation.', safetyNotes: 'Measure from safe standing areas and do not enter traffic or unstable slopes.', requiredEvidence: ['date', 'locationCategory', 'measurements', 'notes'], photoOptional: false, checklist: ['Length and depth recorded', 'Nearby doors, windows, or paths noted', 'Sun and water clues noted', 'At least one uncertainty identified'] },
    designChallenge: { title: 'Foundation bed concept', brief: 'Create or link a Design District concept for a small foundation bed that protects access, respects mature size, provides seasonal structure, and responds to a documented client goal.', requiredElements: ['Linked Design District or independent design record', 'Client goal stated', 'Site constraints recorded', 'Mature sizes reviewed', 'Circulation or maintenance access shown', 'Seasonal interest described', 'Self-review reflection completed'], rubric: ['Requirements addressed', 'Site response documented', 'Mature scale checked', 'Maintenance considered'] },
    questions: [
      question('landscape-design', 1, 'obj-design-analysis', 'multiple-choice', 'What should be confirmed before detailed design begins?', ['A written brief of goals and constraints', 'The final plant order', 'A favorite paving color', 'The installation date regardless of scope'], 'A written brief of goals and constraints', 'The brief defines the design problem.', { promptVariants: ['Which record most directly prevents a concept from solving the wrong problem?'] }),
      question('landscape-design', 2, 'obj-design-analysis', 'multiple-select', 'Which items belong in a site analysis?', ['Sun pattern', 'Circulation', 'Drainage clues', 'Unverified promises'], ['Sun pattern', 'Circulation', 'Drainage clues'], 'Physical conditions and use patterns are analysis inputs.'),
      question('landscape-design', 3, 'obj-design-principles', 'multiple-choice', 'Repeating a plant form along a path most directly supports:', ['Rhythm', 'Soil texture', 'Tax accounting', 'Dormancy'], 'Rhythm', 'Repetition and sequence can create rhythm.'),
      question('landscape-design', 4, 'obj-design-principles', 'true-false', 'Every attractive object in a small garden should act as a focal point.', ['True', 'False'], 'False', 'Too many competing focal points weaken hierarchy.'),
      question('landscape-design', 5, 'obj-design-planting', 'multiple-choice', 'Why should a planting plan show mature widths?', ['To evaluate space, access, and future overlap', 'To guarantee an exact final size', 'To avoid all maintenance', 'To choose pot colors'], 'To evaluate space, access, and future overlap', 'Mature dimensions guide spacing and conflicts but remain estimates.', { promptVariants: ['What is the primary design use of estimated mature spread?'] }),
      question('landscape-design', 6, 'obj-design-planting', 'short-response', 'Name two considerations that can influence spacing besides the label’s mature width.', [], [], 'Habit, airflow, maintenance access, time to coverage, budget, site conditions, and design intent can matter.', { correctAnswerCriteria: ['air', 'access', 'maintenance', 'coverage', 'budget', 'habit', 'site', 'intent'] }),
    ],
  },
  {
    slug: 'irrigation',
    courseTitle: 'Water and Soil Fundamentals',
    courseSummary: 'Understand landscape water movement before selecting or designing an irrigation method.',
    levelTitle: 'Level 1 · Water and Soil Fundamentals',
    levelSummary: 'Infiltration, percolation, drainage, plant water loss, soil storage, mulch, and basic field observations.',
    objectives: [
      { id: 'obj-water-movement', title: 'Explain water entry, movement, storage, and loss', reviewLessonId: 'academy-lesson-irrigation-1', reviewSection: 'Water pathway', remediation: 'Draw arrows for precipitation, infiltration, percolation, runoff, evaporation, and transpiration on one site.' },
      { id: 'obj-water-soils', title: 'Compare water behavior in sandy, clayey, and loamy soils', reviewLessonId: 'academy-lesson-irrigation-2', reviewSection: 'Soil-water behavior', remediation: 'Compare two soils without equating high storage with high plant availability.' },
      { id: 'obj-water-diagnosis', title: 'Distinguish common overwatering and underwatering clues', reviewLessonId: 'academy-lesson-irrigation-3', reviewSection: 'Evidence-led water diagnosis', remediation: 'Check moisture at root depth and record the distribution pattern before choosing a watering response.' },
    ],
    lessons: [
      { moduleTitle: 'Landscape water cycle', moduleSummary: 'Track water from arrival to loss.', title: 'Trace water through a landscape', objectiveIds: ['obj-water-movement'], introduction: 'Irrigation decisions make more sense when water is followed through the entire site system.', body: ['Precipitation or irrigation may infiltrate, run off, collect, evaporate, move through soil, or be taken up by roots. Site cover, slope, compaction, intensity, and initial moisture change the pathway.', 'Transpiration is water loss through plants; evaporation is loss from soil and wet surfaces. Evapotranspiration combines these processes and can inform scheduling, but local values require context.', 'The goal is not simply to apply water. It is to replenish an appropriate root zone without chronic saturation, runoff, overspray, or avoidable loss.'], keyConcepts: ['Applied water can follow several pathways.', 'Evapotranspiration is a planning concept, not a fixed universal schedule.', 'Root-zone replenishment is the practical target.'], vocabulary: ['runoff', 'evaporation', 'transpiration', 'evapotranspiration'], workedExamples: ['A fast hose stream on compacted slope may produce runoff before the root zone is replenished.'], practicalApplication: 'Sketch a water pathway for one planting area.', clientRelevance: 'Explain why longer watering is not always deeper watering if application exceeds infiltration.', commonMistakes: ['Scheduling only by minutes', 'Ignoring runoff'], safetyNotes: ['Keep water and equipment away from electrical hazards and unsafe walking surfaces.'], businessRelevance: 'Documented conditions support responsible scheduling and scope boundaries.', quickChecks: ['How do evaporation and transpiration differ?', 'Why can applied water fail to reach roots?'], summary: 'Manage where water goes, not only how long it runs.', sourceNotes: 'Original educational summary; use local weather, soil, plant, and regulatory guidance for schedules.' },
      { moduleTitle: 'Soil moisture', moduleSummary: 'Connect pore space with usable water.', title: 'Compare soil water-holding behavior', objectiveIds: ['obj-water-soils'], introduction: 'Texture, structure, organic matter, compaction, roots, and container or bed geometry all affect soil moisture.', body: ['Sandy soils generally contain more large pores and often drain quickly while storing less water per depth. Clayey soils can store more total water but move it slowly and hold some too tightly for plants.', 'Loam describes a balanced texture class, not perfect soil. Structure can improve infiltration and aeration across textures; compaction can reduce both.', 'Field capacity, permanent wilting point, and water-holding capacity describe different parts of storage. Plant-available water lies between practical upper and lower limits and varies with conditions.'], keyConcepts: ['Fast drainage and low storage often coincide in sandy soil.', 'High total storage does not mean all water is available.', 'Compaction changes pore continuity.'], vocabulary: ['field capacity', 'permanent wilting point', 'water-holding capacity', 'compaction'], workedExamples: ['Frequent shallow watering may wet only the upper portion of a sandy root zone.'], practicalApplication: 'Compare moisture behavior in two beds or containers after watering.', clientRelevance: 'Use soil behavior to explain why identical schedules can produce different results.', commonMistakes: ['Treating every clay soil as permanently wet', 'Calling loam maintenance-free'], safetyNotes: ['Avoid prolonged skin contact with unknown or contaminated soils.'], businessRelevance: 'Soil behavior informs hydro-zones and maintenance estimates.', quickChecks: ['Why can clay store water yet still stress roots?', 'How does compaction affect infiltration?'], summary: 'Match application to the soil’s movement and storage behavior.', sourceNotes: 'Original summary aligned with standard soil-water concepts.' },
      { moduleTitle: 'Watering diagnosis', moduleSummary: 'Use moisture, pattern, and context.', title: 'Recognize water stress without guessing', objectiveIds: ['obj-water-diagnosis'], introduction: 'Overwatering and underwatering can produce overlapping symptoms, so the root zone and distribution pattern matter.', body: ['Underwatering clues can include dry soil at root depth, loss of turgor, scorched margins, premature leaf drop, or slow growth. Heat and root problems may look similar.', 'Overwatering clues can include persistently saturated soil, low-oxygen root decline, edema, yellowing, soft growth, fungus gnat activity, or odor. None of these alone proves the cause.', 'Check moisture in several locations and depths, inspect emitters or coverage, note recent rainfall, and compare affected and unaffected plants. Mulch can reduce evaporation, but excessive depth against stems creates other risks.'], keyConcepts: ['Symptoms overlap.', 'Distribution and root-depth moisture are essential checks.', 'Mulch must be used with correct depth and placement.'], vocabulary: ['root zone', 'hydro-zone', 'distribution', 'mulch'], workedExamples: ['One wilted shrub at the end of a drip line may signal a clogged emitter rather than a short schedule for the whole zone.'], practicalApplication: 'Perform a five-point moisture and coverage check.', clientRelevance: 'Explain the evidence before changing a controller.', commonMistakes: ['Increasing every zone from one dry spot', 'Piling mulch against trunks'], safetyNotes: ['Local plumbing, backflow, permitting, and licensing rules may apply. Academy work does not authorize regulated irrigation work.'], businessRelevance: 'A recorded coverage check separates repair needs from schedule changes.', quickChecks: ['Why check multiple locations?', 'How can mulch help and harm?'], summary: 'Confirm moisture and distribution before changing water.', sourceNotes: 'Original instructional content; follow local requirements and manufacturer instructions.' },
    ],
    vocabulary: [{ term: 'Infiltration', definition: 'Water entering the soil surface.' }, { term: 'Percolation', definition: 'Water moving through soil.' }, { term: 'Evapotranspiration', definition: 'Combined water loss through evaporation and plant transpiration.' }, { term: 'Field capacity', definition: 'Water remaining after excess gravitational drainage.' }, { term: 'Permanent wilting point', definition: 'A lower soil-water threshold beyond which a plant cannot recover without water.' }, { term: 'Hydro-zone', definition: 'Plants grouped by compatible water needs and site conditions.' }],
    practice: { title: 'Root-zone watering plan', instructions: 'For one real or practice bed, record soil behavior, root-zone depth estimate, slope, sun, mulch, recent rain, and how you would verify that applied water reaches the intended depth.', checklist: ['Soil behavior described', 'Root zone and exposure considered', 'Runoff risk considered', 'Verification method included'] },
    fieldLab: { title: 'Irrigation coverage and moisture inspection', instructions: 'Observe a safe watering event or hand-watered area. Record method, duration, runoff, dry spots, overspray, and root-depth moisture at more than one point. State whether the evidence supports a schedule or maintenance change.', safetyNotes: 'Avoid electrical hazards and slippery surfaces. Do not open regulated assemblies. Local plumbing, backflow, permitting, and licensing requirements may apply.', requiredEvidence: ['date', 'locationCategory', 'measurements', 'notes'], photoOptional: true, checklist: ['Method and duration recorded', 'Multiple points checked', 'Runoff or overspray noted', 'Recommendation tied to evidence'] },
    questions: [
      question('irrigation', 1, 'obj-water-movement', 'multiple-choice', 'Water moving into the soil surface is:', ['Infiltration', 'Transpiration', 'Precipitation rate', 'Winterization'], 'Infiltration', 'Infiltration is surface entry.', { promptVariants: ['Which term describes water crossing from the surface into soil?'] }),
      question('irrigation', 2, 'obj-water-movement', 'multiple-choice', 'Evapotranspiration combines:', ['Evaporation and transpiration', 'Infiltration and runoff', 'Pressure and flow', 'Field capacity and compaction'], 'Evaporation and transpiration', 'The term combines surface evaporation and plant water loss.'),
      question('irrigation', 3, 'obj-water-soils', 'multiple-choice', 'Which statement is generally most accurate?', ['Sandy soil often drains quickly and stores less water per depth', 'Clay soil releases all stored water easily', 'Loam never compacts', 'Texture changes each time mulch is added'], 'Sandy soil often drains quickly and stores less water per depth', 'Large pores often support faster drainage and lower storage.', { promptVariants: ['Which general soil-water comparison is defensible?'] }),
      question('irrigation', 4, 'obj-water-soils', 'true-false', 'All water held by soil is equally available to plant roots.', ['True', 'False'], 'False', 'Some water is held too tightly or is otherwise inaccessible.'),
      question('irrigation', 5, 'obj-water-diagnosis', 'multiple-choice', 'One plant is dry while others on the same drip zone are moist. What should be checked first?', ['The local emitter and root-zone moisture', 'A longer schedule for every zone', 'The paint color of the controller', 'Winterization'], 'The local emitter and root-zone moisture', 'A localized distribution problem should be checked before changing the whole schedule.', { promptVariants: ['A single dry spot appears in an otherwise moist zone. Which first step is most efficient?'] }),
      question('irrigation', 6, 'obj-water-diagnosis', 'multiple-select', 'Which observations help distinguish watering problems?', ['Moisture at several depths', 'Coverage pattern', 'Recent rainfall', 'One symptom with no context'], ['Moisture at several depths', 'Coverage pattern', 'Recent rainfall'], 'Moisture, distribution, and weather context improve the diagnosis.'),
    ],
  },
  {
    slug: 'plant-identification',
    courseTitle: 'Plant Identification Foundations',
    courseSummary: 'Observe morphology, context, and change before assigning a confident name.',
    levelTitle: 'Level 1 · Observation and Identification Method',
    levelSummary: 'Build useful plant descriptions, compare candidates, and document uncertainty.',
    objectives: [
      { id: 'obj-id-morphology', title: 'Describe vegetative and reproductive features', reviewLessonId: 'academy-lesson-plant-identification-1', reviewSection: 'Observable features', remediation: 'Write a description without using a plant name or color alone.' },
      { id: 'obj-id-process', title: 'Use a comparison process to narrow identity', reviewLessonId: 'academy-lesson-plant-identification-2', reviewSection: 'Candidate comparison', remediation: 'Compare two candidates feature by feature and name the missing evidence.' },
      { id: 'obj-id-record', title: 'Create an honest, useful identification record', reviewLessonId: 'academy-lesson-plant-identification-3', reviewSection: 'Evidence and confidence', remediation: 'Revise an absolute claim into an evidence-based confidence statement.' },
    ],
    lessons: [
      { moduleTitle: 'Plant features', moduleSummary: 'Learn a consistent observation vocabulary.', title: 'Describe leaves, stems, flowers, fruit, and habit', objectiveIds: ['obj-id-morphology'], introduction: 'A useful identification begins with features that another person could observe and compare.', body: ['Record leaf arrangement, type, shape, margin, venation, surface, attachment, and smell only when safe. Describe stems, bark, buds, thorns, hairs, and overall habit.', 'Flowers and fruit are often highly informative, but they may be absent. Note number and arrangement of floral parts, inflorescence form, fruit type, and seasonal timing.', 'Photograph the whole plant, its habitat, a representative branch, leaf surfaces and attachment, buds, bark, flowers, and fruit as available. Include scale.'], keyConcepts: ['Use several independent features.', 'Whole-plant habit and close details both matter.', 'Phenology changes what can be observed.'], vocabulary: ['opposite', 'alternate', 'margin', 'inflorescence'], workedExamples: ['“Opposite simple leaves with serrated margins on arching woody stems” is more useful than “green shrub.”'], practicalApplication: 'Create a feature checklist for one unknown plant.', clientRelevance: 'Care and toxicity advice should not rely on an uncertain name.', commonMistakes: ['Using flower color alone', 'Photographing only one leaf'], safetyNotes: ['Do not taste unknown plants; use caution around sap, hairs, thorns, and possible allergens.'], businessRelevance: 'Consistent photos and notes make later sourcing and replacement more reliable.', quickChecks: ['What is leaf arrangement?', 'Why include a scale?'], summary: 'Describe before naming.', sourceNotes: 'Original field-identification instruction.' },
      { moduleTitle: 'Identification process', moduleSummary: 'Compare candidates and eliminate conflicts.', title: 'Narrow candidates with keys, records, and context', objectiveIds: ['obj-id-process'], introduction: 'Identification is a comparison process, not a resemblance contest.', body: ['Begin broadly: woody or herbaceous, growth habit, leaf arrangement, major reproductive features, and habitat. Then compare candidate descriptions or a suitable key.', 'Use location, season, cultivation, and habitat as supporting context, not proof. Cultivars, juvenile growth, pruning, stress, and escaped garden plants can distort expectations.', 'Reject a candidate when a reliable observed feature conflicts. Seek another feature, specimen, or qualified confirmation when consequences are significant.'], keyConcepts: ['Elimination is as important as similarity.', 'Context supports but does not prove identity.', 'Consequences determine how much confirmation is needed.'], vocabulary: ['dichotomous key', 'candidate', 'cultivar', 'phenology'], workedExamples: ['Two shrubs share white flowers, but one has alternate leaves and the specimen has opposite leaves.'], practicalApplication: 'Create a two-candidate comparison table.', clientRelevance: 'State when a name is provisional before discussing edibility or toxicity.', commonMistakes: ['Forcing a key choice when neither fits', 'Ignoring a contradictory feature'], safetyNotes: ['Do not make consumption or treatment decisions from a practice identification.'], businessRelevance: 'Careful identification reduces incorrect ordering and client advice.', quickChecks: ['What should happen when a key choice does not fit?', 'How can habitat help without proving identity?'], summary: 'Compare, eliminate, and confirm in proportion to risk.', sourceNotes: 'Original identification-method summary.' },
      { moduleTitle: 'Plant records', moduleSummary: 'Store evidence and link existing plant data.', title: 'Record confidence, sources, and field observations', objectiveIds: ['obj-id-record'], introduction: 'A plant record should preserve what was seen, how a name was reached, and what remains uncertain.', body: ['Store the observation date, location category, images, features, candidate names, source notes, confidence, and reviewer if any. Field observation is different from verified identity.', 'Link to an existing Plant Intelligence record when appropriate rather than creating a duplicate database. Update field notes without overwriting curated plant traits.', 'Use confidence labels such as unknown, candidate, probable, or confirmed by a named reliable source. A photograph alone is not automatically verified.'], keyConcepts: ['Evidence and identity are separate fields.', 'Confidence should be explicit.', 'Link rather than duplicate plant records.'], vocabulary: ['voucher', 'provisional', 'confidence', 'source note'], workedExamples: ['“Probable highbush blueberry; leaf and twig features match, but fruit and flower were absent” preserves uncertainty.'], practicalApplication: 'Build a complete provisional plant record.', clientRelevance: 'Transparent confidence prevents unsupported safety claims.', commonMistakes: ['Deleting an earlier candidate without preserving history', 'Claiming automatic photo verification'], safetyNotes: ['Unknown plant records must not be used to authorize eating or handling.'], businessRelevance: 'Evidence-rich records support future site visits and replacements.', quickChecks: ['What belongs in a confidence statement?', 'Why link an existing plant record?'], summary: 'Preserve evidence, sources, and uncertainty.', sourceNotes: 'Original recordkeeping guidance.' },
    ],
    vocabulary: [{ term: 'Opposite', definition: 'Two leaves or buds occurring at the same node on opposite sides.' }, { term: 'Alternate', definition: 'One leaf or bud per node, alternating along a stem.' }, { term: 'Margin', definition: 'The edge of a leaf blade.' }, { term: 'Inflorescence', definition: 'The arrangement of flowers on a plant.' }, { term: 'Phenology', definition: 'Seasonal timing of life-cycle events.' }, { term: 'Provisional', definition: 'Tentative and subject to confirmation.' }],
    practice: { title: 'Blind morphology description', instructions: 'Describe an unknown or familiar plant without naming it. Include habit, leaves, stems, reproductive features if present, scale, date, and context.', checklist: ['Whole-plant habit described', 'At least four leaf or stem features', 'Scale and date included', 'Missing evidence stated'] },
    fieldLab: { title: 'Provisional plant identification record', instructions: 'Observe one plant and create a provisional record with images or a detailed description, feature checklist, two candidates where needed, source notes, confidence, and a safe next confirmation step.', safetyNotes: 'Do not taste or closely handle an unknown plant. This lab does not automatically verify identification.', requiredEvidence: ['date', 'locationCategory', 'notes'], photoOptional: false, checklist: ['Whole plant and details documented', 'Observable features recorded', 'Confidence labeled', 'No unsupported safety or edibility claim'] },
    questions: [
      question('plant-identification', 1, 'obj-id-morphology', 'multiple-choice', 'Which description is most useful for identification?', ['Pretty green leaves', 'Opposite simple leaves with serrated margins', 'A nice shrub', 'Probably native'], 'Opposite simple leaves with serrated margins', 'It records multiple observable features.', { promptVariants: ['Which field note provides the strongest morphological evidence?'] }),
      question('plant-identification', 2, 'obj-id-morphology', 'multiple-select', 'Which photographs strengthen a plant record?', ['Whole habit', 'Leaf attachment', 'Flowers or fruit', 'Only a decorative filter'], ['Whole habit', 'Leaf attachment', 'Flowers or fruit'], 'Context and diagnostic details are complementary.'),
      question('plant-identification', 3, 'obj-id-process', 'multiple-choice', 'A candidate has alternate leaves, but the specimen clearly has opposite leaves. What should you do?', ['Reject or reconsider that candidate', 'Ignore the conflict', 'Change the observation', 'Claim confirmation'], 'Reject or reconsider that candidate', 'A reliable contradictory feature matters.'),
      question('plant-identification', 4, 'obj-id-process', 'true-false', 'A plant’s location alone proves its identity.', ['True', 'False'], 'False', 'Location is context, not conclusive morphology.'),
      question('plant-identification', 5, 'obj-id-record', 'multiple-choice', 'A photo resembles blueberry, but flowers and fruit are absent. Which record is most honest?', ['Confirmed blueberry', 'Probable candidate with missing evidence noted', 'Safe to eat', 'No record needed'], 'Probable candidate with missing evidence noted', 'The confidence should match the available evidence.', { promptVariants: ['When key reproductive features are missing, how should confidence be recorded?'] }),
      question('plant-identification', 6, 'obj-id-record', 'short-response', 'Name two details that belong in a provisional identification record.', [], [], 'Date, location category, observed features, photos, candidates, sources, confidence, and missing evidence are useful.', { correctAnswerCriteria: ['date', 'location', 'feature', 'photo', 'candidate', 'source', 'confidence', 'missing'] }),
    ],
  },
  {
    slug: 'plant-health',
    courseTitle: 'Plant Health and Diagnostic Foundations',
    courseSummary: 'Recognize patterns, separate causes, and choose low-risk integrated responses.',
    levelTitle: 'Level 1 · Diagnosis and Integrated Plant Health',
    levelSummary: 'A practical diagnostic sequence for cultural, abiotic, pest, and disease possibilities.',
    objectives: [
      { id: 'obj-health-pattern', title: 'Collect useful symptom, sign, pattern, and timeline evidence', reviewLessonId: 'academy-lesson-plant-health-1', reviewSection: 'Diagnostic evidence', remediation: 'Rewrite a diagnosis as a pattern-and-timeline observation.' },
      { id: 'obj-health-causes', title: 'Separate abiotic and biotic possibilities', reviewLessonId: 'academy-lesson-plant-health-2', reviewSection: 'Cause categories', remediation: 'List one cultural, environmental, pest, and disease possibility for the same symptom.' },
      { id: 'obj-health-ipm', title: 'Use integrated plant management thresholds and follow-up', reviewLessonId: 'academy-lesson-plant-health-3', reviewSection: 'Integrated response', remediation: 'Choose a monitoring or cultural action before a treatment and define when escalation is justified.' },
    ],
    lessons: [
      { moduleTitle: 'Diagnostic evidence', moduleSummary: 'Collect patterns before naming causes.', title: 'Read symptoms, signs, distribution, and time', objectiveIds: ['obj-health-pattern'], introduction: 'A credible diagnosis begins with a complete case history and a pattern across the plant and site.', body: ['Identify the plant as reliably as needed, then record affected parts, symptom progression, distribution on each plant, distribution across the site, and timing.', 'Look for direct signs such as fungal structures, insects, frass, webbing, eggs, or bacterial ooze, while recognizing that presence does not always establish primary cause.', 'Ask what changed: installation, weather, watering, grade, herbicide use, construction, pruning, fertilizer, mulch, soil disturbance, or nearby plant decline.'], keyConcepts: ['Pattern can separate site-wide and localized causes.', 'A sign is more direct than a symptom but still needs interpretation.', 'History often reveals nonliving stress.'], vocabulary: ['symptom', 'sign', 'incidence', 'severity'], workedExamples: ['Uniform injury on one side of several species suggests a different path than spots spreading within one host species.'], practicalApplication: 'Complete a diagnostic intake without naming a cause.', clientRelevance: 'Ask neutral questions that do not assign blame.', commonMistakes: ['Diagnosing from one close-up', 'Ignoring recent site work'], safetyNotes: ['Avoid contact with unknown organisms, animal waste, pesticides, and unstable trees.'], businessRelevance: 'Consistent intake records make referrals and follow-up efficient.', quickChecks: ['How do incidence and severity differ?', 'Why photograph affected and unaffected areas?'], summary: 'Collect the whole pattern and timeline.', sourceNotes: 'Original diagnostic-process instruction.' },
      { moduleTitle: 'Cause categories', moduleSummary: 'Keep multiple plausible paths open.', title: 'Compare abiotic stress, pests, and disease', objectiveIds: ['obj-health-causes'], introduction: 'The same visible symptom can arise from water, roots, temperature, chemistry, insects, pathogens, or multiple interacting stresses.', body: ['Abiotic problems include drought, saturation, compaction, temperature injury, salt, nutrient imbalance, chemical injury, planting depth, and mechanical damage. They do not spread between plants like a reproducing agent.', 'Biotic causes include insects, mites, fungi, bacteria, nematodes, viruses, wildlife, and parasitic plants. Their patterns depend on host, life cycle, weather, and movement.', 'Use discriminating evidence: root condition, moisture, damage pattern, host range, signs, progression, and laboratory support when consequences or uncertainty justify it.'], keyConcepts: ['One symptom has many possible causes.', 'Abiotic and biotic stress can interact.', 'A discriminating check should change the decision.'], vocabulary: ['abiotic', 'biotic', 'host range', 'vector'], workedExamples: ['Leaf scorch on multiple unrelated plants along a paved edge may point toward heat, drought, or salt exposure.'], practicalApplication: 'Build and rank a differential list of four causes.', clientRelevance: 'Explain that testing can prevent an unnecessary treatment.', commonMistakes: ['Calling every leaf spot fungal', 'Treating a secondary pest as the original cause'], safetyNotes: ['Follow regulations and labels; refer hazardous trees, regulated pests, and uncertain chemical cases.'], businessRelevance: 'Accurate triage prevents ineffective labor and product costs.', quickChecks: ['What makes a check discriminating?', 'Can abiotic stress and pests occur together?'], summary: 'Compare categories and seek evidence that separates them.', sourceNotes: 'Original instructional synthesis.' },
      { moduleTitle: 'Integrated response', moduleSummary: 'Prevent, monitor, and intervene proportionally.', title: 'Use integrated plant health management', objectiveIds: ['obj-health-ipm'], introduction: 'Integrated plant management combines prevention, correct identification, monitoring, thresholds, and the lowest-risk effective response.', body: ['Begin with compatible plants, healthy stock, good installation, sanitation, water management, and soil protection. Monitor known risks at useful times.', 'Decide whether action is needed based on plant value, safety, likely damage, life stage, natural enemies, client tolerance, and feasibility. Not every organism requires control.', 'Prefer cultural, mechanical, biological, or targeted options suited to the cause. If a pesticide is considered, the label is the law; confirm site, pest, plant, timing, protective equipment, and local requirements. Verify results.'], keyConcepts: ['Prevention and monitoring are active management.', 'Thresholds connect evidence to action.', 'Treatment success must be checked.'], vocabulary: ['threshold', 'cultural control', 'biological control', 'monitoring'], workedExamples: ['A few aphids with active predators on vigorous growth may call for monitoring rather than broad treatment.'], practicalApplication: 'Create an action ladder from observation to referral.', clientRelevance: 'Explain why “do nothing yet” can be a professional monitored decision.', commonMistakes: ['Treating without identification', 'Skipping follow-up'], safetyNotes: ['Pesticide selection and application may be regulated and require licensing. Academy completion grants no authorization.'], businessRelevance: 'Thresholds keep service recommendations consistent and transparent.', quickChecks: ['What factors influence an action threshold?', 'What closes an IPM cycle?'], summary: 'Prevent, identify, monitor, act proportionally, and verify.', sourceNotes: 'Original IPM summary; consult current label and local extension or regulatory guidance.' },
    ],
    vocabulary: [{ term: 'Symptom', definition: 'A plant response to stress or injury.' }, { term: 'Sign', definition: 'Direct observable evidence of a causal organism or agent.' }, { term: 'Abiotic', definition: 'Caused by a nonliving factor.' }, { term: 'Biotic', definition: 'Caused by a living agent.' }, { term: 'Threshold', definition: 'A defined point at which action is justified.' }, { term: 'Integrated management', definition: 'Coordinated prevention, monitoring, and proportionate control methods.' }],
    practice: { title: 'Diagnostic differential', instructions: 'Use a provided or real nonhazardous plant-health case. Record the pattern, timeline, four plausible causes, one check for each, and the lowest-risk next step.', checklist: ['Pattern and timeline recorded', 'Abiotic and biotic causes included', 'Discriminating checks identified', 'Follow-up date included'] },
    fieldLab: { title: 'Plant-health monitoring record', instructions: 'Observe one safely accessible plant. Record affected and unaffected tissue, site distribution, moisture context, recent changes, possible signs, confidence, and a follow-up plan. Do not claim visual confirmation you do not have.', safetyNotes: 'Do not climb, sample hazardous material, handle pesticides, or approach unstable trees. Refer significant risk.', requiredEvidence: ['date', 'locationCategory', 'notes'], photoOptional: false, checklist: ['Affected and unaffected areas documented', 'Pattern and recent changes recorded', 'Multiple causes considered', 'Safe next step and follow-up recorded'] },
    questions: [
      question('plant-health', 1, 'obj-health-pattern', 'multiple-choice', 'Which record best supports diagnosis?', ['Pattern, affected parts, timeline, and site context', 'One close-up with no date', 'A product recommendation', 'The plant price'], 'Pattern, affected parts, timeline, and site context', 'Diagnosis depends on case history and pattern.', { promptVariants: ['What information adds the most diagnostic value at intake?'] }),
      question('plant-health', 2, 'obj-health-pattern', 'true-false', 'Finding an insect on a declining plant always proves it caused the decline.', ['True', 'False'], 'False', 'The insect may be incidental or secondary.'),
      question('plant-health', 3, 'obj-health-causes', 'multiple-choice', 'Several unrelated species show scorch along the same paved edge. Which category deserves early consideration?', ['Abiotic site stress', 'One host-specific pathogen only', 'Pollination failure', 'Dormancy'], 'Abiotic site stress', 'A cross-species site pattern can indicate heat, water, salt, or chemical exposure.'),
      question('plant-health', 4, 'obj-health-causes', 'multiple-select', 'Which checks can help separate possible causes?', ['Root condition', 'Soil moisture', 'Host range', 'Guessing from color alone'], ['Root condition', 'Soil moisture', 'Host range'], 'These observations can discriminate among cause categories.'),
      question('plant-health', 5, 'obj-health-ipm', 'multiple-choice', 'A few aphids are present with natural predators and little damage. What is a defensible first response?', ['Monitor and define an action threshold', 'Apply every available pesticide', 'Remove the entire landscape', 'Promise there will be no damage'], 'Monitor and define an action threshold', 'Low pressure with natural enemies may not justify immediate treatment.', { promptVariants: ['When pest pressure is low and beneficial insects are active, what is the integrated response?'] }),
      question('plant-health', 6, 'obj-health-ipm', 'short-response', 'Name two elements of an integrated plant-health decision.', [], [], 'Prevention, identification, monitoring, threshold, cultural or mechanical options, targeted treatment, and follow-up are relevant.', { correctAnswerCriteria: ['prevent', 'identify', 'monitor', 'threshold', 'cultural', 'mechanical', 'target', 'follow'] }),
    ],
  },
  {
    slug: 'client-communication',
    courseTitle: 'Client Consultation Foundations',
    courseSummary: 'Discover needs, explain tradeoffs, and document professional next steps.',
    levelTitle: 'Level 1 · Discovery, Recommendations, and Boundaries',
    levelSummary: 'A repeatable consultation structure with clear, calm, honest communication.',
    objectives: [
      { id: 'obj-client-discovery', title: 'Use discovery questions to clarify goals and constraints', reviewLessonId: 'academy-lesson-client-communication-1', reviewSection: 'Consultation structure', remediation: 'Rewrite three solution-led questions as open discovery questions.' },
      { id: 'obj-client-explain', title: 'Explain recommendations and tradeoffs in plain language', reviewLessonId: 'academy-lesson-client-communication-2', reviewSection: 'Recommendation structure', remediation: 'Practice a recommendation using observation, consequence, options, and next step.' },
      { id: 'obj-client-boundaries', title: 'Set scope, uncertainty, and follow-up boundaries', reviewLessonId: 'academy-lesson-client-communication-3', reviewSection: 'Written recap', remediation: 'Draft a recap that separates confirmed scope, exclusions, assumptions, and client decisions.' },
    ],
    lessons: [
      { moduleTitle: 'Discovery', moduleSummary: 'Listen for the problem beneath the requested product.', title: 'Lead a purposeful client discovery conversation', objectiveIds: ['obj-client-discovery'], introduction: 'A consultation should uncover use, priorities, constraints, decision process, budget comfort, care capacity, and what success means.', body: ['Begin with open questions: how the space is used, what feels unsuccessful, who maintains it, what must remain, and what a successful first year would look like.', 'Clarify priorities by asking clients to compare outcomes. “Low maintenance,” “natural,” and “finished” mean different things to different people.', 'Summarize what you heard and ask for correction. Record required functions, preferences, exclusions, site unknowns, budget range, timeline, and the next decision.'], keyConcepts: ['Ask before recommending.', 'Translate vague words into observable outcomes.', 'Confirm the summary.'], vocabulary: ['discovery', 'priority', 'constraint', 'decision criteria'], workedExamples: ['“Low maintenance” becomes monthly professional care, no deadheading, and clear winter structure.'], practicalApplication: 'Practice a ten-question consultation and three-sentence recap.', clientRelevance: 'Clients feel heard when their priorities return in the recommendation.', commonMistakes: ['Talking about plants too early', 'Assuming budget from property appearance'], safetyNotes: ['Respect privacy and do not record audio without clear permission.'], businessRelevance: 'Clear discovery improves lead fit and reduces redesign.', quickChecks: ['How can you clarify “low maintenance”?', 'What should close discovery?'], summary: 'Listen, clarify, rank, and confirm.', sourceNotes: 'Original professional-communication instruction.' },
      { moduleTitle: 'Recommendations', moduleSummary: 'Explain reasons, options, and consequences.', title: 'Recommend without lecturing or overpromising', objectiveIds: ['obj-client-explain'], introduction: 'A confident recommendation is specific about the site, connected to the client’s goal, and honest about tradeoffs.', body: ['Use a simple structure: observation, relevance, recommendation, option, and next step. Replace jargon or explain it in a sentence.', 'When a requested plant does not fit, affirm the desired outcome, state the site conflict, and offer alternatives that preserve the outcome. Availability and living materials require conditional language.', 'Discuss cost through scope, labor, expertise, logistics, risk, and ongoing value. Do not attack the client’s budget; offer phased or reduced-scope paths when appropriate.'], keyConcepts: ['Connect advice to client priorities.', 'Preserve the desired outcome when changing the requested solution.', 'Options create informed choice.'], vocabulary: ['tradeoff', 'alternative', 'allowance', 'phasing'], workedExamples: ['“You want fruit near the patio; this area has four hours of sun, so I recommend herbs here and fruit in the sunnier side bed.”'], practicalApplication: 'Record a written or spoken response to a wrong-plant scenario.', clientRelevance: 'Plain reasons and options protect trust.', commonMistakes: ['Saying “because that is the rule”', 'Guaranteeing stock or survival'], safetyNotes: ['Do not make toxicity, structural, legal, or medical claims beyond reliable evidence and scope.'], businessRelevance: 'Transparent choices improve approvals and change-order conversations.', quickChecks: ['What should come before the recommendation?', 'How can an alternative preserve a client goal?'], summary: 'Explain the reason, preserve the goal, and offer a next step.', sourceNotes: 'Original communication framework.' },
      { moduleTitle: 'Boundaries and follow-up', moduleSummary: 'Put expectations in a usable record.', title: 'Close with scope, assumptions, and next actions', objectiveIds: ['obj-client-boundaries'], introduction: 'Professional confidence includes saying what is known, what requires verification, and what is outside the current service.', body: ['Recap decisions, open questions, deliverables, exclusions, allowances, client responsibilities, schedule assumptions, payment steps, and who owns the next action.', 'Use calibrated language for living systems: expected, typical, likely, subject to availability, or dependent on care. State warranty terms rather than implying guaranteed survival.', 'Send or save the recap promptly and connect it to the existing client or project when real. A practice scenario should remain clearly labeled and avoid polluting business records.'], keyConcepts: ['Boundaries protect both parties.', 'Assumptions must be visible.', 'The next action needs an owner.'], vocabulary: ['scope', 'exclusion', 'assumption', 'change order'], workedExamples: ['The recap notes that final cultivar depends on confirmed nursery inventory and any substitution requires approval.'], practicalApplication: 'Write a consultation closeout with one uncertainty and one owner-assigned next action.', clientRelevance: 'Written clarity reduces surprise.', commonMistakes: ['Leaving verbal exclusions undocumented', 'Using certainty where conditions vary'], safetyNotes: ['Local contract and consumer rules may apply; use qualified legal advice for policy language.'], businessRelevance: 'Written scope and change paths reduce unpaid work.', quickChecks: ['What belongs beside a schedule assumption?', 'Why label practice records?'], summary: 'Close in writing with decisions, boundaries, and ownership.', sourceNotes: 'Original operations and communication guidance; not legal advice.' },
    ],
    vocabulary: [{ term: 'Discovery', definition: 'Structured inquiry used to understand needs before recommending.' }, { term: 'Constraint', definition: 'A condition that limits or shapes acceptable solutions.' }, { term: 'Tradeoff', definition: 'A benefit gained or cost accepted when choosing among options.' }, { term: 'Scope', definition: 'The defined work and deliverables included in an agreement.' }, { term: 'Exclusion', definition: 'Work or responsibility explicitly outside scope.' }, { term: 'Assumption', definition: 'A condition treated as true pending confirmation.' }],
    practice: { title: 'Consultation recap', instructions: 'Use a real authorized conversation or a practice scenario. Record goals, constraints, preferences, budget language, unknowns, recommendation, exclusions, and next actions.', checklist: ['Goals and constraints separated', 'Client language translated into outcomes', 'Uncertainty and exclusions visible', 'Next action has an owner'] },
    fieldLab: { title: 'Client explanation practice record', instructions: 'Respond in writing to a scenario where the requested plant does not suit the site. Include the desired outcome, observed conflict, two alternatives, a tradeoff, one uncertainty, and a next step.', safetyNotes: 'Use a practice scenario unless you have permission to store a real client exchange. Do not record audio without consent.', requiredEvidence: ['date', 'notes'], photoOptional: true, checklist: ['Desired outcome acknowledged', 'Site conflict explained plainly', 'Alternatives offered', 'No unsupported guarantee'] },
    questions: [
      question('client-communication', 1, 'obj-client-discovery', 'multiple-choice', 'A client asks for a “low-maintenance” garden. What is the best next question?', ['What tasks and frequency feel acceptable to you?', 'Which fertilizer should I buy?', 'Can I ignore the budget?', 'Should every plant be evergreen?'], 'What tasks and frequency feel acceptable to you?', 'The phrase needs to be translated into observable expectations.', { promptVariants: ['How should a designer clarify the phrase “low maintenance”?'] }),
      question('client-communication', 2, 'obj-client-discovery', 'multiple-select', 'Which topics belong in discovery?', ['How the space is used', 'Maintenance capacity', 'Budget comfort', 'A final recommendation before listening'], ['How the space is used', 'Maintenance capacity', 'Budget comfort'], 'Discovery covers use, constraints, decisions, and resources.'),
      question('client-communication', 3, 'obj-client-explain', 'multiple-choice', 'A requested fruit tree lacks enough sun. Which response is strongest?', ['Acknowledge the fruit goal, explain the light conflict, and offer sunnier placement or alternatives', 'Say no without a reason', 'Promise fruit anyway', 'Ignore the site'], 'Acknowledge the fruit goal, explain the light conflict, and offer sunnier placement or alternatives', 'It preserves the goal while explaining the constraint.'),
      question('client-communication', 4, 'obj-client-explain', 'true-false', 'Professional confidence requires pretending uncertainty does not exist.', ['True', 'False'], 'False', 'Clear limits and verification needs are professional.'),
      question('client-communication', 5, 'obj-client-boundaries', 'multiple-choice', 'What is the best close to a consultation?', ['A written recap with decisions, assumptions, and owned next actions', 'No record', 'An undefined promise', 'A surprise invoice'], 'A written recap with decisions, assumptions, and owned next actions', 'The recap preserves shared expectations.', { promptVariants: ['Which follow-up record most reduces consultation misunderstandings?'] }),
      question('client-communication', 6, 'obj-client-boundaries', 'short-response', 'Name two items that should be explicit in a consultation recap.', [], [], 'Scope, exclusions, decisions, unknowns, assumptions, client responsibilities, schedule, payment, and next actions are useful.', { correctAnswerCriteria: ['scope', 'exclusion', 'decision', 'unknown', 'assumption', 'responsib', 'schedule', 'payment', 'next'] }),
    ],
  },
  {
    slug: 'business-operations',
    courseTitle: 'Landscape Business Operations Foundations',
    courseSummary: 'Convert a defined scope into a responsible estimate, work plan, and reviewable record.',
    levelTitle: 'Level 1 · Scope, Estimating, and Delivery',
    levelSummary: 'Whole-project costs, margin awareness, sourcing uncertainty, and operational closeout.',
    objectives: [
      { id: 'obj-business-scope', title: 'Turn a request into measurable scope and exclusions', reviewLessonId: 'academy-lesson-business-operations-1', reviewSection: 'Observable scope', remediation: 'Rewrite one vague service as deliverables, quantities, assumptions, and exclusions.' },
      { id: 'obj-business-estimate', title: 'Calculate whole-project cost and price', reviewLessonId: 'academy-lesson-business-operations-2', reviewSection: 'Cost, markup, and margin', remediation: 'Recalculate a practice job including owner labor, overhead allowance, and contingency.' },
      { id: 'obj-business-delivery', title: 'Connect approvals, sourcing, schedule, and records', reviewLessonId: 'academy-lesson-business-operations-3', reviewSection: 'Operational handoff', remediation: 'Build a pre-installation checklist with owners and dependencies.' },
    ],
    lessons: [
      { moduleTitle: 'Scope', moduleSummary: 'Make promises observable.', title: 'Define deliverables, assumptions, and change boundaries', objectiveIds: ['obj-business-scope'], introduction: 'Estimating begins only after the work is described clearly enough to count, schedule, and verify.', body: ['Name deliverables in observable terms: consultation count, drawing type, bed area, plants, soil preparation, edging, mulch, irrigation concept, installation, disposal, or follow-up.', 'Record quantities, quality or size standards, access, utilities, existing-condition assumptions, client responsibilities, exclusions, allowances, and acceptance criteria.', 'Define how additions, concealed conditions, and substitutions are approved. A change order is a communication and record process, not merely an extra charge.'], keyConcepts: ['Scope must be countable or verifiable.', 'Assumptions and exclusions affect price.', 'Changes require documented approval.'], vocabulary: ['deliverable', 'allowance', 'exclusion', 'change order'], workedExamples: ['“Install garden” becomes measured bed preparation, listed plants and sizes, mulch depth, cleanup, and one watering walkthrough.'], practicalApplication: 'Rewrite a vague request as a scope checklist.', clientRelevance: 'Observable scope lets clients compare what is actually included.', commonMistakes: ['Pricing an undefined bed', 'Leaving disposal or access unaddressed'], safetyNotes: ['Licensing, permits, utility location, and subcontractor requirements vary by work and place.'], businessRelevance: 'Clear scope is the foundation of profit and client trust.', quickChecks: ['What makes a deliverable observable?', 'Why are assumptions priced?'], summary: 'Define the work before calculating it.', sourceNotes: 'Original business-operations instruction; not legal advice.' },
      { moduleTitle: 'Estimating', moduleSummary: 'Count every cost and distinguish margin from markup.', title: 'Price the whole project', objectiveIds: ['obj-business-estimate'], introduction: 'A price must cover direct costs, labor, overhead, uncertainty, and the desired return.', body: ['Direct costs can include plants, materials, delivery, disposal, rentals, permits, subcontractors, paid labor, owner labor, mileage, and payment fees. Confirm whether tax applies locally.', 'Overhead supports the business beyond one project. Allocate it consistently rather than hoping material markup covers insurance, software, tools, sales, administration, and nonbillable time.', 'Markup is added to cost; margin is profit divided by selling price. They are not interchangeable. Add a documented contingency or allowance for defined uncertainty, then check the final margin.'], keyConcepts: ['Owner time has a cost.', 'Markup and margin use different bases.', 'Contingency is not a substitute for defining scope.'], vocabulary: ['direct cost', 'overhead', 'markup', 'gross margin'], workedExamples: ['If total cost is $800 and price is $1,000, gross profit is $200 and gross margin is 20%, while markup on cost is 25%.'], practicalApplication: 'Build a practice estimate using the existing Estimate workspace.', clientRelevance: 'Explain price through scope and delivery rather than disclosing unsupported shortcuts.', commonMistakes: ['Marking up plants while omitting labor', 'Treating deposits as revenue already earned'], safetyNotes: ['Tax and accounting treatment varies; use qualified local professionals.'], businessRelevance: 'Whole-project costing reveals whether accepted work supports the company.', quickChecks: ['How do markup and margin differ?', 'Name three often-missed project costs.'], summary: 'Count the entire delivery cost and check margin.', sourceNotes: 'Original estimating instruction; accounting and tax examples are educational.' },
      { moduleTitle: 'Delivery system', moduleSummary: 'Connect dependencies from approval through closeout.', title: 'Build a reliable project handoff and closeout', objectiveIds: ['obj-business-delivery'], introduction: 'A sold scope becomes successful work only when decisions, materials, access, labor, weather, communication, and records align.', body: ['Before scheduling, confirm approval, deposit terms, final selections, substitutions, quantities, availability, delivery, site access, utilities, permits, responsibilities, and weather-sensitive dependencies.', 'Assign an owner and date to each next action. Keep plant sourcing, estimates, expenses, photos, design decisions, and client approvals linked to the existing project record.', 'Close out with completion checks, care instructions, warranty terms, final billing, unresolved items, before-and-after documentation, and a scheduled follow-up when included.'], keyConcepts: ['Dependencies control reliable dates.', 'Records should link to the project once.', 'Closeout includes care and unresolved items.'], vocabulary: ['dependency', 'procurement', 'closeout', 'variance'], workedExamples: ['An installation date remains tentative until the plant hold, access, deposit, and weather-sensitive preparation are confirmed.'], practicalApplication: 'Build a preflight and closeout checklist for a practice project.', clientRelevance: 'Clear milestones make delays and responsibilities understandable.', commonMistakes: ['Scheduling from hope', 'Creating disconnected copies of sourcing data'], safetyNotes: ['Use qualified trades for regulated or hazardous work.'], businessRelevance: 'Operational discipline protects cash flow and reputation.', quickChecks: ['What turns a target date into a reliable date?', 'What belongs in closeout?'], summary: 'Link the work, owners, dependencies, and final record.', sourceNotes: 'Original project-operations summary.' },
    ],
    vocabulary: [{ term: 'Deliverable', definition: 'An observable product or service included in scope.' }, { term: 'Allowance', definition: 'A budgeted amount for an item not finally selected or known.' }, { term: 'Direct cost', definition: 'A cost attributable to delivering a particular project.' }, { term: 'Overhead', definition: 'Business cost not tied solely to one project.' }, { term: 'Gross margin', definition: 'Gross profit divided by selling price.' }, { term: 'Dependency', definition: 'A condition or task that must be resolved before another can proceed reliably.' }],
    practice: { title: 'Whole-project estimate audit', instructions: 'Use a practice estimate. Check materials, paid and owner labor, travel, delivery, disposal, equipment, subcontractors, overhead allowance, contingency, tax assumptions, deposit, and final margin.', checklist: ['Scope and quantities visible', 'Owner labor included', 'Overhead and uncertainty addressed', 'Margin checked after final price'] },
    fieldLab: { title: 'Practice project preflight', instructions: 'Choose a practice or clearly labeled non-live project. Build a pre-installation checklist with approvals, plant availability, access, materials, labor, weather, safety, client responsibilities, and owners.', safetyNotes: 'Do not create real commitments, purchases, or regulated work from a practice record.', requiredEvidence: ['date', 'notes'], photoOptional: true, checklist: ['Practice status labeled', 'Dependencies listed', 'Each next action has an owner', 'Closeout steps included'] },
    questions: [
      question('business-operations', 1, 'obj-business-scope', 'multiple-choice', 'Which scope is most estimable?', ['Install a nice garden', 'Prepare 180 square feet, install listed plants and two inches of mulch, then clean up', 'Do whatever is needed', 'Make it beautiful'], 'Prepare 180 square feet, install listed plants and two inches of mulch, then clean up', 'It identifies measurable deliverables.', { promptVariants: ['Which description is sufficiently observable for estimating?'] }),
      question('business-operations', 2, 'obj-business-scope', 'multiple-select', 'Which items can materially affect scope?', ['Access', 'Disposal', 'Existing-condition assumptions', 'An unrelated favorite color'], ['Access', 'Disposal', 'Existing-condition assumptions'], 'They change labor, logistics, risk, or deliverables.'),
      question('business-operations', 3, 'obj-business-estimate', 'calculation', 'A practice job costs $800 and sells for $1,000. What is gross margin percentage?', ['20%', '25%', '80%', '125%'], '20%', 'Gross profit is $200; $200 divided by the $1,000 selling price is 20%.', { promptVariants: ['Total cost is $800 and price is $1,000. Which gross margin is correct?'] }),
      question('business-operations', 4, 'obj-business-estimate', 'true-false', 'Owner labor can be omitted because it is not paid to an employee.', ['True', 'False'], 'False', 'Owner time is part of delivery cost and capacity.'),
      question('business-operations', 5, 'obj-business-delivery', 'multiple-choice', 'Which action makes an installation date more reliable?', ['Confirm approvals, availability, access, and dependencies', 'Schedule before scope', 'Ignore delivery timing', 'Assume weather cannot change'], 'Confirm approvals, availability, access, and dependencies', 'Dependencies determine whether the work can start as planned.', { promptVariants: ['What should occur before treating a target installation date as firm?'] }),
      question('business-operations', 6, 'obj-business-delivery', 'short-response', 'Name two records that should stay linked to the project during delivery.', [], [], 'Design decisions, estimates, sourcing, approvals, expenses, photos, tasks, and completion records are useful.', { correctAnswerCriteria: ['design', 'estimate', 'sourc', 'approval', 'expense', 'photo', 'task', 'completion'] }),
    ],
  },
];

export const ACADEMY_CURRICULUM = configs.map(buildCourse);

export const ACADEMY_LEVELS = ACADEMY_CURRICULUM.flatMap(item => item.levels);
export const ACADEMY_LESSONS = ACADEMY_CURRICULUM.flatMap(item => item.lessons);
export const ACADEMY_OBJECTIVES = ACADEMY_CURRICULUM.flatMap(item => item.objectives);
export const ACADEMY_QUESTIONS = ACADEMY_CURRICULUM.flatMap(item => item.questions);

export function academyCourseForSchool(schoolId) {
  return ACADEMY_CURRICULUM.find(item => item.school.id === schoolId) || null;
}

export function academyLevel(levelId) {
  return ACADEMY_LEVELS.find(item => item.id === levelId) || null;
}

export function academyLesson(lessonId) {
  return ACADEMY_LESSONS.find(item => item.id === lessonId) || null;
}

export function academyActivity(activityId) {
  for (const curriculum of ACADEMY_CURRICULUM) {
    const items = [curriculum.vocabulary, curriculum.practice, curriculum.scenarioAssessment, curriculum.fieldLab, curriculum.designChallenge, curriculum.finalAssessment].filter(Boolean);
    const found = items.find(item => item.id === activityId);
    if (found) return found;
  }
  return null;
}

export function academySearchIndex() {
  return ACADEMY_CURRICULUM.flatMap(curriculum => [
    { id: curriculum.school.id, title: curriculum.school.title, detail: curriculum.school.summary, kind: 'School' },
    { id: curriculum.course.id, title: curriculum.course.title, detail: curriculum.course.summary, kind: 'Course' },
    ...curriculum.modules.map(item => ({ id: item.id, title: item.title, detail: item.summary, kind: 'Module' })),
    ...curriculum.lessons.map(item => ({ id: item.id, title: item.title, detail: `${curriculum.school.title} · Lesson`, kind: 'Lesson', text: [item.introduction, item.body, item.keyConcepts, item.vocabulary].flat().join(' ') })),
    ...curriculum.objectives.map(item => ({ id: item.id, title: item.title, detail: `${curriculum.school.title} · Learning objective`, kind: 'Objective' })),
    ...curriculum.vocabulary.terms.map(item => ({ id: `${curriculum.vocabulary.id}-${item.term}`, title: item.term, detail: `${item.definition} · Vocabulary`, kind: 'Vocabulary' })),
  ]);
}

export { IRRIGATION_LEVEL_FRAMEWORK };
