export const CLIENT_CONFIDENCE_SCENARIOS = [
  ['wrong-plant', 'Client wants the wrong plant for the site', 'A client wants a moisture-loving flowering shrub against a hot, dry west-facing wall.', ['Acknowledge the desired flower or mood', 'Explain the heat and moisture conflict', 'Offer site-suited alternatives or a better location', 'Avoid guaranteeing performance'], ['goal', 'heat', 'moisture', 'alternative']],
  ['availability', 'Requested plant may not be available', 'A client expects an exact cultivar that has not been reserved with a nursery.', ['State that availability must be verified', 'Describe which traits a substitution must preserve', 'Require approval before substitution', 'Explain schedule or price effects'], ['availability', 'verify', 'trait', 'approval']],
  ['budget', 'Unrealistic budget expectations', 'A client requests a fully mature-looking front landscape on a budget that does not cover the stated scope.', ['Respect the budget', 'Connect price to defined scope', 'Offer phasing or reduced scope', 'Avoid shaming or unsupported discounts'], ['budget', 'scope', 'phase', 'option']],
  ['instant-results', 'Instant mature results', 'A client wants every bed densely filled on installation day with no future thinning or maintenance.', ['Explain establishment and mature spread', 'Describe overplanting consequences', 'Offer strategic temporary color', 'Set a realistic visual timeline'], ['mature', 'spacing', 'establish', 'timeline']],
  ['foundation-roots', 'Roots near a foundation', 'A client is worried that every shrub root near the house will damage the foundation.', ['Ask about the actual structure and issue', 'Explain that plant size and siting matter', 'Avoid structural guarantees', 'Recommend qualified assessment where warranted'], ['structure', 'size', 'site', 'qualified']],
  ['fruit-low-light', 'Fruit trees in insufficient light', 'A client wants fruit trees in a courtyard receiving about four hours of direct sun.', ['Acknowledge the harvest goal', 'Explain light needs and likely tradeoffs', 'Offer a sunnier location or shade-tolerant edible layers', 'Avoid promising a crop'], ['harvest', 'light', 'alternative', 'crop']],
  ['drainage', 'Drainage problems', 'A client asks you to solve standing water after seeing one puddle following a major storm.', ['Document timing and pattern', 'Explain limits of one observation', 'Separate planting advice from engineered drainage', 'Recommend further assessment when needed'], ['observe', 'pattern', 'limit', 'assess']],
  ['overwatering', 'Overwatering', 'A client waters every zone daily because one plant wilted in midsummer.', ['Check root-zone moisture and distribution', 'Explain overlapping stress symptoms', 'Recommend evidence-based schedule changes', 'Check the individual emitter or plant'], ['moisture', 'distribution', 'symptom', 'emitter']],
  ['low-maintenance', 'Low-maintenance garden', 'A client wants a garden that requires no maintenance at all.', ['Clarify acceptable tasks and frequency', 'Explain that living landscapes require care', 'Offer a lower-maintenance palette and service plan', 'Set seasonal expectations'], ['clarify', 'care', 'season', 'plan']],
  ['design-fee', 'Why the design costs money', 'A client asks why they should pay for a design before buying plants.', ['Connect design to site analysis and goals', 'Explain mature-size and quantity planning', 'Describe how design reduces avoidable rework', 'State the actual deliverables'], ['analysis', 'mature', 'rework', 'deliverable']],
  ['labor-cost', 'Questions labor costs', 'A client compares installation labor with the hourly wage of a general helper.', ['Explain the included scope and skilled responsibilities', 'Mention logistics, preparation, cleanup, and business overhead', 'Avoid criticizing other workers', 'Offer scope options instead of hiding costs'], ['scope', 'skill', 'logistic', 'overhead']],
  ['substitution', 'Plant substitution', 'A nursery cannot supply one key plant two days before installation.', ['Verify the design role and required traits', 'Check price, size, timing, and site fit', 'Obtain client approval', 'Update the project and estimate records'], ['trait', 'site', 'approval', 'record']],
  ['pet-safety', 'Pet safety', 'A client asks whether every proposed plant is completely safe for their dog.', ['Take the concern seriously', 'Check reliable plant-specific sources', 'Avoid universal safety guarantees', 'Discuss access, supervision, and alternatives'], ['source', 'specific', 'guarantee', 'alternative']],
  ['toxic-plants', 'Toxic plants', 'A client asks if a plant found from a photograph is edible.', ['Do not authorize consumption from an uncertain identification', 'Explain the identification limit', 'Seek reliable confirmation', 'Offer known alternatives'], ['not eat', 'uncertain', 'confirm', 'alternative']],
  ['irrigation-request', 'Client wants irrigation', 'A client asks for a full irrigation installation during a garden consultation.', ['Clarify the performance goal and site', 'Explain concept versus regulated installation scope', 'Mention local backflow, plumbing, permitting, or licensing requirements', 'Refer qualified work where required'], ['goal', 'scope', 'local', 'qualified']],
  ['greenhouse-outdoors', 'Greenhouse plant outdoors', 'A client wants a tender greenhouse plant to remain outdoors through a Delaware winter.', ['Explain cold exposure and hardiness limits', 'Offer seasonal container or overwintering options', 'Name uncertainty from microclimate', 'Avoid survival guarantees'], ['cold', 'hardiness', 'season', 'microclimate']],
  ['warranty', 'Warranty or plant survival', 'A client asks for a guarantee that every living plant will survive regardless of weather or care.', ['Explain actual warranty terms', 'Separate covered installation issues from care and extreme conditions', 'Provide care responsibilities', 'Document follow-up and exclusions'], ['warranty', 'care', 'condition', 'document']],
].map(([id, title, scenario, modelPoints, keywords]) => ({ id: `academy-client-scenario-${id}`, title, scenario, modelPoints, keywords }));

export const CLIENT_CLARITY_CHECKLIST = ['Acknowledges the client’s underlying goal', 'Uses plain language', 'Explains the site or business reason', 'Offers a realistic next step'];
export const CLIENT_PROFESSIONALISM_CHECKLIST = ['Avoids blame or ridicule', 'States uncertainty honestly', 'Avoids unsupported guarantees', 'Keeps scope and responsibilities clear'];

export function clientConceptCoverage(scenario, response) {
  const normalized = String(response || '').toLowerCase();
  const matched = scenario.keywords.filter(keyword => normalized.includes(keyword));
  return { matched, missing: scenario.keywords.filter(keyword => !matched.includes(keyword)), coverage: Math.round(matched.length / scenario.keywords.length * 100) };
}
